apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/gke-cluster-test-454517/locations/us-central1-c/clusters/gke-demo-cluster
